//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Glogalozacion.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Glogalozacion.Recursos.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AreaStr {
            get {
                return ResourceManager.GetString("AreaStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculo.
        /// </summary>
        public static string CirculoStr {
            get {
                return ResourceManager.GetString("CirculoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        public static string CuadradoStr {
            get {
                return ResourceManager.GetString("CuadradoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fromas.
        /// </summary>
        public static string FormasStr {
            get {
                return ResourceManager.GetString("FormasStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Formas.
        /// </summary>
        public static string HeaderStr {
            get {
                return ResourceManager.GetString("HeaderStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista vacía de formas!.
        /// </summary>
        public static string ListaFormasVacia {
            get {
                return ResourceManager.GetString("ListaFormasVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimetro.
        /// </summary>
        public static string PerimetroStr {
            get {
                return ResourceManager.GetString("PerimetroStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangulo.
        /// </summary>
        public static string RectanguloStr {
            get {
                return ResourceManager.GetString("RectanguloStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        public static string TotalStr {
            get {
                return ResourceManager.GetString("TotalStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecio.
        /// </summary>
        public static string TrapecioStr {
            get {
                return ResourceManager.GetString("TrapecioStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulo.
        /// </summary>
        public static string TrianguloStr {
            get {
                return ResourceManager.GetString("TrianguloStr", resourceCulture);
            }
        }
    }
}
